name: formio_flutter
description: A flutter package to let users consume any form created with formIO.js
version: 0.10.0
homepage: https://github.com/Crdzbird/formio_flutter

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  rxdart: ^0.27.5
  http: ^0.13.5
  image: ^3.2.0
  math_expressions: ^2.3.1
  file_picker: ^5.0.1
  flutter_neumorphic: ^3.2.0
  font_awesome_flutter: ^9.2.0
  assorted_layout_widgets: ^7.0.0
  universal_io: ^2.0.4
  intl: ^0.17.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
